// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Link struct {
	ID        int64
	WishID    sql.NullInt64
	LinkIndex int64
	Url       sql.NullString
}

type User struct {
	Name         string
	Passwordhash []byte
}

type Wish struct {
	ID           int64
	WishlistUuid sql.NullInt64
	WishIndex    int64
	Name         sql.NullString
	Description  sql.NullString
	ImageUrl     sql.NullString
	Reserved     sql.NullInt64
}

type Wishlist struct {
	Uuid     string
	UserName string
	Title    sql.NullString
}
