// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Link struct {
	ID     int64
	WishID int64
	Url    string
}

type Session struct {
	ID       string
	UserName string
	Expire   time.Time
}

type User struct {
	Name         string
	Passwordhash []byte
}

type Visited struct {
	ID           int64
	UserName     string
	WishlistUuid string
	Timestamp    time.Time
}

type Wish struct {
	ID           int64
	WishlistUuid string
	Name         string
	Description  string
	ImageUrl     string
	Reserved     int64
	Active       int64
	OrderIndex   int64
}

type Wishlist struct {
	Uuid      string
	UserName  string
	Title     string
	Timestamp sql.NullTime
	Access    int64
}
